# Generated by Django 3.2.9 on 2021-11-15 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breathwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('how_to', models.TextField()),
                ('benefits', models.TextField()),
                ('inhale_1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('exhale_1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('inhale_2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('exhale_2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('inhale_3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('exhale_3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('inhale_4', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('exhale_4', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('post_inhale_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('post_exhale_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('post_reps_breath_hold', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recovery_inhale', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recovery_exhale', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recovery_bh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('inhale_reps', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('exhale_reps', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('breath_reps', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('youtube_link', models.URLField(blank=True, max_length=1024, null=True)),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elements.element')),
            ],
        ),
    ]
