# Generated by Django 3.2.7 on 2021-12-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breathwork',
            name='primary_color',
            field=models.CharField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='breathwork',
            name='secondary_color',
            field=models.CharField(default=True, max_length=254),
        ),
    ]
