# Generated by Django 3.2.7 on 2021-12-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20211209_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breathwork',
            name='primary_color',
            field=models.CharField(default='lightsteelblue', max_length=254),
        ),
        migrations.AlterField(
            model_name='breathwork',
            name='secondary_color',
            field=models.CharField(default='lightpink', max_length=254),
        ),
    ]
