# Generated by Django 3.2.7 on 2021-12-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('djstripe', '0008_2_5'),
        ('account', '0003_auto_20211205_1822'),
        ('socialaccount', '0004_auto_20211205_1822'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='element',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
