# Generated by Django 3.2.9 on 2021-12-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20211202_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='description',
            new_name='element_description',
        ),
    ]
