# Generated by Django 3.2.7 on 2021-12-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_rename_description_element_element_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='sub_benefits',
            field=models.TextField(null=True),
        ),
    ]
